import manCategory from './men-category.webp';
import womanCategory from './woman-category.webp';
import hatCategory from './hat-category.webp';
import jacketCategory from './jacket-category.webp';
import sneakerCategory from './sneaker-category.webp';
import logo from './crown.svg';
import cart from './cart.svg';
import trash from './trash.svg';
const Image =  {cart, manCategory, womanCategory, hatCategory, jacketCategory, sneakerCategory, logo, trash};
export default Image;